name: crypting
version: "0.10.5"
license: "BSD-3-Clause"
date: 2024-09-03
description: |
    Hashes and Crypto in GAP

authors:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/

maintainers:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/crypting/
readme: README.md
packageinfo: https://gap-packages.github.io/crypting/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/crypting/releases/download/v0.10.5/crypting-0.10.5.tar.gz

abstract: |
    The <span class="pkgname">crypting</span> package provides some cryptographic primitives so that the <span class="pkgname">JupyterKernel</span> package works.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>PT24</span>]   <b class='BibAuthor'>Pfeiffer, M. and GAP Team, T.</b>,
     <i class='BibTitle'>crypting, Hashes and Crypto in GAP,
             Version 0.10.5</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/crypting/">https://gap-packages.github.io/crypting/</a></span>.
    </p>
    

bibtex: |
    @misc{ crypting,
      author =           {Pfeiffer, M. and GAP Team, T.},
      title =            {{crypting}, Hashes and Crypto in GAP, {V}ersion 0.10.5},
      month =            {Sep},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href       {https://gap-packages.github.io/crypting/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{crypting/}}},
      printedkey =       {PT24}
    }

